### ISSUE TITLE
Wait states lasting longer than specified

### ISSUE THREAD

**Issue by joschaschmiedt** [esi-neuroscience/ARCADE#21]
For versions 2.0 to 2.1.2 `State`s lasted ca 10% longer than specified in their `State.duration` property (see original issue http://git.esi.local/it/ARCADE/-/issues/75 from 2017). After testing using digital events (TTL pulses) and `QueryPerformanceCounter` it was confirmed that the calls to ` java.lang.Thread.sleep` or `WaitForMultipleObjects` where indeed lasting too long, e.g. 
```
requested =  5000 ms -> result = 5461 ms
requested =   200 ms -> result =  221 ms
requested =  1000 ms -> result = 1093 ms
```
This however only happened when ARCADE was fully launched (ControlScreen, StimSterver, NidaqServer running), and not when calling the sleep functions/system calls from within an interactive, single MATLAB session. Setting a debug point just before the call also made the problem disappear.

A workaround using a polling method was implemented in 40470aac8753d2a81201e25f0f24146121d3b364 (version 2.1.3):
https://github.com/esi-neuroscience/ARCADE/blob/0cde6b204736a9954fb9f511b313e4bed3ee5ceb/arcade/Core/State.m#L101-L110

The workaround however does introduce a high CPU load and this issue should be revisited in a future version.

**Comment by joschaschmiedt** [comment]
The problem probably originates from the interaction of MATLAB with the OS context/scheduling. There are two other processes that I could imagine playing a role:

1. The ControlScreen is an interactive GUI doing polling and redrawing everything at a 5 ms interval (https://github.com/esi-neuroscience/ARCADE/blob/0cde6b204736a9954fb9f511b313e4bed3ee5ceb/arcade/ControlScreen/runControlScreen.m#L112)
2. The StimServer, which is running in full-screen mode and thereby potentially affects the drawing/scheduling of other processes. 

Their effects could be tested by enabling or disabling them. The effect of the full-screen mode of StimServer could be tested putting the StimServer into windowed mode (press Alt+Enter or dragging a different window into it) and testing whether this has an effect on the sleep durations. If this indeed is the case, we still don’t really know whether this is coming from Windows or MATLAB.

**Comment by jsdpag** [comment]
Following advice of Joscha Schmiedt and Michael Stephan, tested the effect of launching ARCADE processes without any parent/child relationship between them; thus without using the ProcessManager package.

1. Disable process launching in Core process by commenting out [lines 22 - 79](https://github.com/esi-neuroscience/ARCADE/blob/0cde6b204736a9954fb9f511b313e4bed3ee5ceb/arcade/Core/launch_processes.m#L22-L79) and [line 106](https://github.com/esi-neuroscience/ARCADE/blob/0cde6b204736a9954fb9f511b313e4bed3ee5ceb/arcade/Core/launch_processes.m#L106) in [launch_processes.m](https://github.com/esi-neuroscience/ARCADE/blob/master/arcade/Core/launch_processes.m). [Line 106](https://github.com/esi-neuroscience/ARCADE/blob/0cde6b204736a9954fb9f511b313e4bed3ee5ceb/arcade/Core/launch_processes.m#L106) must be disabled otherwise it triggers the Control Screen to close.
2. Manually start [NidaqServer.exe](https://github.com/esi-neuroscience/ARCADE/blob/master/arcade/DaqServer/NidaqServer.exe), [EyeLinkServer.exe](https://github.com/esi-neuroscience/ARCADE/blob/master/arcade/EyeServer/EyeLinkServer.exe), [StimServer.exe](https://github.com/esi-neuroscience/ARCADE/blob/master/arcade/StimServer/StimServer.exe), and [MatlabControlScreen.bat](https://github.com/esi-neuroscience/ARCADE/blob/master/arcade/ControlScreen/MatlabControlScreen.bat) by double-clicking their icons. Alternatively, these can be started from a batch file.
3. Open a normal session of Matlab and run [add_arcade_to_path.m](https://github.com/esi-neuroscience/ARCADE/blob/master/arcade/add_arcade_to_path.m).
4. Add conditional breakpoint at [State.m line 105](https://github.com/esi-neuroscience/ARCADE/blob/0cde6b204736a9954fb9f511b313e4bed3ee5ceb/arcade/Core/State.m#L105) to stop when a specific state is reached. This can be done using expression `strcmp( obj.name , <state name> )` where `<state name>` is a state that is waiting for an eye window event that will never happen during testing.
5. Execute [runCore.m](https://github.com/esi-neuroscience/ARCADE/blob/master/arcade/Core/runCore.m).
6. Once execution pauses at line 105 of State.m, execute the following from the Matlab command line:
`>> tic , WaitForEvents( 1 , obj.waitEvents , false , <timer duration> ) ; toc`
7. Test different magnitudes of `<timer duration>`, such as 1, 10, 100, 500, 1000 (in milliseconds). `toc` returns measured duration of the `WaitForMultipleObjects` timer, in seconds.
8. With ARCADE processes launched separately from each other, the timer overrun or underrun is limited to a constant range e.g. +/- 15ms.
9. In contrast, if no lines are disabled in [launch_processes.m](https://github.com/esi-neuroscience/ARCADE/blob/master/arcade/Core/launch_processes.m), then the timer overrun will be scaled by the size of the requested timer duration.
10. When ARCADE processes are launched separately, then the constant range of timer overrun can be limited to within 1 to 2ms by calling [`timeBeginPeriod( 1 )`](https://docs.microsoft.com/en-us/windows/win32/api/timeapi/nf-timeapi-timebeginperiod).

The results above were confirmed using high-resulution time stamping provided by [QueryPerformanceCounter](https://docs.microsoft.com/en-us/windows/win32/api/profileapi/nf-profileapi-queryperformancecounter).
